from __future__ import annotations

from pathlib import Path


SRC_ROOT = Path(__file__).resolve().parents[1]

PREVIEW_WIDTH = 1280
PREVIEW_HEIGHT = 720

DEFAULT_SCRFD_MODEL = SRC_ROOT.parents[1] / "models" / "scrfd_person_2.5g.onnx"
DEFAULT_DETECTION_INPUT_WIDTH = 640
DEFAULT_DETECTION_INPUT_HEIGHT = 640
DEFAULT_DETECTION_SCORE_THRESHOLD = 0.5
DEFAULT_DETECTION_NMS_THRESHOLD = 0.45
DEFAULT_CAMERA_FPS = 30

DEFAULT_TRACKING_IOU_THRESHOLD = 0.3
DEFAULT_TRACKING_MAX_MISSED = 8

DEFAULT_ENTRANCE_LINE_AXIS = "x"
DEFAULT_ENTRANCE_LINE_POSITION = 0.55
DEFAULT_OUTSIDE_SIDE = "less"
DEFAULT_ENTRANCE_MIN_HISTORY = 3
DEFAULT_ENTRY_SESSION_LINE_AXIS = "x"
DEFAULT_ENTRY_SESSION_LINE_POSITION = 0.70

DEFAULT_EVIDENCE_DIR = SRC_ROOT / "evidence"
DEFAULT_EVIDENCE_PRE_FRAMES = 4
DEFAULT_EVIDENCE_POST_FRAMES = 4
DEFAULT_EVIDENCE_CROP_MARGIN = 0.15

DEFAULT_INSIGHTFACE_CACHE_ROOT = SRC_ROOT / ".cache" / "insightface"
DEFAULT_EMBEDDING_RUNS_DIR = SRC_ROOT / "embedding_runs"
DEFAULT_IDENTITY_RUNS_DIR = SRC_ROOT / "identity_runs"
DEFAULT_ENTRY_SESSION_RUNS_DIR = SRC_ROOT / "entry_session_runs"

DEFAULT_EMBEDDING_MODEL_PACK = "buffalo_l"
DEFAULT_EMBEDDING_DET_WIDTH = 640
DEFAULT_EMBEDDING_DET_HEIGHT = 640
DEFAULT_EMBEDDING_DET_THRESH = 0.45

DEFAULT_SHOP_ID = "shop_001"
DEFAULT_CAMERA_ID = "entrance_cam_001"
DEFAULT_MERGE_WINDOW_SECONDS = 2.0
DEFAULT_MIN_FACE_SIMILARITY = 0.68
DEFAULT_AMBIGUITY_FACE_SIMILARITY = 0.55
DEFAULT_MIN_SAME_CAMERA_SIMILARITY = 0.80
